const TRANSLATIONS = {
  ja: {
    "title": "岡山エコツーリズム — DISCOVER OKAYAMA",
    "nav.home": "トップ",
    "nav.what": "エコツーリズムとは",
    "nav.programs": "体験プログラム紹介",
    "nav.env": "環境保全",
    "nav.access": "アクセス",
    "nav.contact": "お問い合わせ",
    "hero.eyebrow": "観光と学び。",
    "hero.title": "岡山のエコツーリズム",
    "hero.lead": "自然を感じ、文化を学び、未来へつなぐ新しい旅のかたちです。",
    "cta.book": "予約する",
    "cta.explore": "体験を探す",
    "programs.title": "体験プログラム紹介",
    "programs.mizushima.title": "みずしまエコツアー",
    "programs.mizushima.text": "水島の公害の歴史と回復を学ぶツアー。",
    "programs.yamanori.title": "山乗渓谷リバートレッキング",
    "programs.yamanori.text": "ブナ林や渓流を楽しむ自然散策。",
    "programs.cruise.title": "水島エコクルーズ",
    "programs.cruise.text": "海洋ごみや環境問題を学ぶ船上ツアー。",
    "programs.canoe.title": "旭川カヌーエコツアー",
    "programs.canoe.text": "旭川をカヌーで巡り、街と自然を同時に体験。",
    "cta.details": "詳細を見る",
    "about.title": "エコツーリズムとは？",
    "about.text": "自然や文化を感じ、学びながら地域の環境保全や暮らしの豊かさにつながる旅のかたちです。",
    "env.title": "環境保全のための取り組み",
    "env.text": "地域と連携した清掃活動や教育プログラムを実施しています。",
    "access.title": "アクセス",
    "access.text": "各プログラムの拠点への行き方を掲載しています。",
    "footer.terms": "利用規約",
    "footer.privacy": "プライバシーポリシー",
    "footer.company": "運営会社",
    "footer.jobs": "採用情報",
    "footer.copyright": "© 2025 Discover Okayama"
  },

  en: {
    "title": "Okayama Ecotourism — DISCOVER OKAYAMA",
    "nav.home": "Home",
    "nav.what": "What is Ecotourism",
    "nav.programs": "Programs",
    "nav.env": "Environment",
    "nav.access": "Access",
    "nav.contact": "Contact",
    "hero.eyebrow": "Discover & Learn.",
    "hero.title": "Ecotourism in Okayama",
    "hero.lead": "Feel the nature, learn the culture, and connect to the future.",
    "cta.book": "Book Now",
    "cta.explore": "Explore Programs",
    "programs.title": "Experience Programs",
    "programs.mizushima.title": "Mizushima Eco Tour",
    "programs.mizushima.text": "Learn about pollution and recovery in Mizushima.",
    "programs.yamanori.title": "Yamanori Valley Trekking",
    "programs.yamanori.text": "Walk through forests and streams in Yamanori Valley.",
    "programs.cruise.title": "Mizushima Eco Cruise",
    "programs.cruise.text": "A boat tour to learn about marine litter and environmental issues.",
    "programs.canoe.title": "Asahigawa Canoe Eco Tour",
    "programs.canoe.text": "Paddle the Asahigawa to enjoy city views and nature.",
    "cta.details": "See details",
    "about.title": "What is Ecotourism?",
    "about.text": "Travel that connects feeling nature and learning culture to local conservation and livelihoods.",
    "env.title": "Conservation efforts",
    "env.text": "We run cleanups and educational programs with local partners.",
    "access.title": "Access",
    "access.text": "Directions to the program bases are listed here.",
    "footer.terms": "Terms",
    "footer.privacy": "Privacy Policy",
    "footer.company": "Company",
    "footer.jobs": "Careers",
    "footer.copyright": "© 2025 Discover Okayama"
  },

  vi: {
    "title": "Du lịch sinh thái Okayama — DISCOVER OKAYAMA",
    "nav.home": "Trang chủ",
    "nav.what": "Ecotourism là gì",
    "nav.programs": "Chương trình",
    "nav.env": "Bảo tồn",
    "nav.access": "Truy cập",
    "nav.contact": "Liên hệ",
    "hero.eyebrow": "Du lịch và học hỏi.",
    "hero.title": "Du lịch sinh thái Okayama",
    "hero.lead": "Cảm nhận thiên nhiên, học nền văn hóa và kết nối cho tương lai.",
    "cta.book": "Đặt chỗ",
    "cta.explore": "Tìm chương trình",
    "programs.title": "Chương trình trải nghiệm",
    "programs.mizushima.title": "Tour Mizushima",
    "programs.mizushima.text": "Tìm hiểu ô nhiễm và phục hồi ở Mizushima.",
    "programs.yamanori.title": "Trekking thung lũng Yamanori",
    "programs.yamanori.text": "Đi bộ qua rừng và suối để tận hưởng thiên nhiên.",
    "programs.cruise.title": "Cruise sinh thái Mizushima",
    "programs.cruise.text": "Tour trên tàu học về rác biển và vấn đề môi trường.",
    "programs.canoe.title": "Tour canoe Asahigawa",
    "programs.canoe.text": "Khám phá Asahigawa bằng canoe, vừa ngắm cảnh vừa trải nghiệm thiên nhiên.",
    "cta.details": "Xem chi tiết",
    "about.title": "Ecotourism là gì?",
    "about.text": "Hình thức du lịch kết nối cảm nhận thiên nhiên, học văn hoá và bảo tồn địa phương.",
    "env.title": "Nỗ lực bảo tồn",
    "env.text": "Thực hiện dọn dẹp và chương trình giáo dục cùng cộng đồng địa phương.",
    "access.title": "Truy cập",
    "access.text": "Hướng dẫn đường đi tới điểm tổ chức chương trình.",
    "footer.terms": "Điều khoản",
    "footer.privacy": "Chính sách bảo mật",
    "footer.company": "Công ty",
    "footer.jobs": "Tuyển dụng",
    "footer.copyright": "© 2025 Discover Okayama"
  }
};
